### ISSUE TITLE
Support for Windows 2016

### ISSUE THREAD

**Issue by hean01-cendio** [rdesktop/rdesktop#101]
rdesktop should support Windows 2016, any issue created related to this platform should reference this issue for a nice overview of what issue affects 2016 server.

Any testers out there that could do some basic testing of rdesktop and windows 2016 ?

**Comment by zjcnew** [comment]
No one answer？

**Comment by joshudson** [comment]
I'm still waiting for mergeback for Window 10. I will start on Windows Server 2016 shortly after.

**Comment by joshudson** [comment]
Update: My branch just works on Windows Server 2016 provided the OS is configured to allow it to display a logon GUI to remote desktop.

**Comment by hean01-cendio** [comment]
@joshudson , what does "provided the OS is configured to allow it to display a logon GUI to remote desktop" actually mean ?

**Comment by jhudsoncedaron** [comment]
It is possible to configure a Windows OS to require the client to prompt for username and password rather than remoting in without a password and have the server display a GUI prompt. Despite the fact that rdesktop is perfectly capable of prompting itself, configuring the server to require this causes rdesktop to not work for a reason I do not understand. This is not new with 2016 but seems to exist since 2008.

**Comment by hean01-cendio** [comment]
@joshudson ah ok. Didn't know about that. Could you put up a new issue and describe how to configure and reproduce and I will take a loot at it.

**Comment by joshudson** [comment]
I can now confirm that the "non GUI" login screen configuration is not the default, but I don't know what switch controls it.

**Comment by pierresouchay** [comment]
I'll be pleased to test on Windows 2016 with Kerberos from Linux workstation, for now, it fails (I supposed it lacks the option in Windows 2016 to allow credential-less logins)

**Comment by hean01-cendio** [comment]
@pierresouchay, can you provide more details about the failure ? (Describe your setup, explain what you expect and give details about what happend)

**Comment by pierresouchay** [comment]
I was looking to connect to Windows server 2016 without any password, just with my domain user and its kerberos ticket.

What I am doing is:

```shell
$ kinit myuser@MY.DOMAIN
$ klist 
Default principal: myuser@MY.DOMAIN

Valid starting       Expires              Service principal
06/07/2017 14:11:49  07/07/2017 00:11:49  krbtgt/MY.DOMAIN@MY.DOMAIN
	renew until 07/07/2017 14:11:45

$ rdesktop my_windows_2016_server.my.domain
```
The connection fails -> it initializes properly in the login window to user MY.DOMAIN\myuser but says password is wrong

If I then list the tickets, I have:
```shell
$ klist
Default principal: p.souchay@PAR.AD.CRITEO.PREPROD

Valid starting       Expires              Service principal
06/07/2017 14:11:49  07/07/2017 00:11:49  krbtgt/MY.DOMAIN@MY.DOMAIN
	renew until 07/07/2017 14:11:45
06/07/2017 14:14:41  07/07/2017 00:11:49  TERMSRV/my_windows_2016_server@
	renew until 07/07/2017 14:11:45
06/07/2017 14:14:41  07/07/2017 00:11:49  TERMSRV/my_windows_2016_server@MY.DOMAIN
	renew until 07/07/2017 14:11:45
```
So, to me, it seems rdesktop did his job, (except the strange ticket TERMSRV/my_windows_2016_server@ without any realm at the end) but connection fails.

In the Windows log, I have just a bad password error (I can give you the complete error if your want).

But I have since seen this entry: https://social.msdn.microsoft.com/Forums/en-US/da074f0f-0887-4151-88ea-19a671ed91d9/is-it-possible-to-do-true-kerberos-sso-using-rdp-?forum=os_windowsprotocols

So I suppose that what I want to do cannot work.

Regards

**Comment by hean01-cendio** [comment]
@pierresouchay Ah ok, that is not possible as you found my post on msdn... NLA = network level authentication  and is used for authenticating servers and prevent MITM attacks.

**Comment by pierresouchay** [comment]
@hean01-cendio You mean that disabling NLA would allow my use-case ?

**Comment by hean01-cendio** [comment]
@pierresouchay, no, RDP does not have any SSO feature and a password is always needed to be provided. one need to integrate rdesktop with something like gnome-keyring or equivalent to get SSO capabilities.

You should interpret NLA security as: Can I trust sharing my password with remote host

**Comment by hean01-cendio** [comment]
We have done extended testing using rdesktop against Windows 2016 RDS cluster which now works good.
