### ISSUE TITLE
The configure file is not find

### ISSUE THREAD

**Issue by TianShiHeiDe** [rdesktop/rdesktop#120]
I did not find the configure file in the source package. Where can i find it?

**Comment by kenaycock** [comment]
Hi,

I believe you need to run automake first to generate the configure script.

Ken

On May 21, 2017 05:14, "TianShiHeiDe" <notifications@github.com> wrote:

I did not find the configure file in the source package. Where can i find
it?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rdesktop/rdesktop/issues/120>, or mute the thread

**Comment by hean01-cendio** [comment]
@TianShiHeiDe , The README.md describes how to setup the build system, see bootstrap script.
