### ISSUE TITLE
Missing Lefthand Support

### ISSUE THREAD

**Issue by ncws** [rdesktop/rdesktop#15]
In KDE or XFCE or GNOME with switched mouse-button's, the left-hand-support works not through in the RDP-Session. I change in the xkeymap.c the MOUSE_FLAG_BUTTON1 and  MOUSE_FLAG_BUTTON2 to solve my problem. IMHO this "bug" was not in the Version 1.8.2?
##

**Comment by yu210148** [comment]
I've been using variations on steelman's patch (https://sourceforge.net/p/rdesktop/patches/155/) with rdesktop for years. I've added it in and put it on pull request #56

**Comment by samhed** [comment]
I can verify that it works the same way with Microsoft's RDP client on Windows 10. If I use lefthand mouse settings locally, the behavior will not go through to the RDP session.

**Comment by hean01-cendio** [comment]
With findings of @samhed,  we should consistently do as the Microsoft RDP client in this case. The swap of mouse buttons is a settings within the remote user session. I don't actually see the problem, when you as user actually can configure how the mouse buttons should behave in the remote session.

**Comment by ncws** [comment]
I think that a Linux RDP client should have a better usability than the original Microsoft client. If a left-handed user on Windows needs to switch to many RDP servers, then he must switch the mouse buttons in each session. Just because the RDP client does not consider the current user settings.

At least a Linux user has the possibilities to customize the source code. :-)

**Comment by hean01-cendio** [comment]
@ncws I fully agree with the principle but i think you missing my point.

In a normal RDS environment the configuration for switch mouse buttons for left handed is done once for the user which is stored with the user profile.

Adding left hand support flag to rdesktop will not "force" lefthand support in the remote RDP session, just flip mouse buttons on client side to fool the server. This means that in a standard RDS environment were the user will configure his user profile to have switched mouse buttons, the -m option will not work as adviced eg. "lefthand  support" due to it will flip back buttons to normal behaviour.

This is an inconsistency that we generally wants to avoid.
