### ISSUE TITLE
Enhancement: add a switch to NOT provide a password

### ISSUE THREAD

**Issue by posgnach** [rdesktop/rdesktop#191]
Hello,

this is just a proposal. I have a shortcut on my desktop that runs rdesktop and connects to my laptop, which is running windows 10.
After commit 1aaafc80c037f57c3742ccb25b279467fcbf58b5 this shortcut broke, since rdesktop wants a password. I do not wish to write the password in the shortcut and I do not wish to run rdesktop from a terminal.
Can we opt out from providing a password? Windows 10 asks me to type it anyway.

**Comment by uglym8** [comment]
Hello,

> After commit 1aaafc8 this shortcut broke, since rdesktop wants a password. I do not wish to write the password in the shortcut and I do not wish to run rdesktop from a terminal.

First of all, note that I don't advocate against your proposal in any way.
Having said this I can propose the following as a temporary workaround: you can provide the arbitrary password in your shortcut and later enter the right password when TS asks you to.

>Windows 10 asks me to type it anyway.

Why? 
I've just checked this and if the password is right you don't have to enter it again.

**Comment by Sturmungandir** [comment]
> Why?
I've just checked this and if the password is right you don't have to enter it again.

I don't know. Could it be a feature of Windows 10 when it is part of a domain?
It will ask for a password again, through the usual Windows login screen.
It does not matter which password I provide to rdesktop.

**Comment by uglym8** [comment]
> I don't know. Could it be a feature of Windows 10 when it is part of a domain?

Do you provide the domain (i.e. **-d**) info as well?

**Comment by Sturmungandir** [comment]
Yes I do

**Comment by uglym8** [comment]
Really strange.
I've got no W10 which is a part of a domain so unfortunately I'm unable to verify this:(

**Comment by Sturmungandir** [comment]
Well, I don't really mind, since I am not allowed to write the true password anywhere, but I mind that rdesktop asks me for a password. As a workaround, I am supplying a fake password

**Comment by hean01-cendio** [comment]
@Sturmungandir I'm not really in for adding a switch to disable the required password. Would your case be solved if you not forced to open a terminal ? Then you could provided a password from a pop-up UI prompt like gnome-ssh-askpass like this:

     /usr/libexec/openssh/gnome-ssh-askpass "RDP Remote password" | rdesktop -p - -u user -d DOMAIN server

**Comment by Sturmungandir** [comment]
Well, point is that Windows is asking for a password in any case. Having also rdesktop asking me for a password is simply... annoying because I would have to type it twice. Windows is simply ignoring whatever password I type after the -p switch so I just hardcoded a single character in my shortcut after the -p switch. Rdesktop is happy and Windows will ask for a password like always

**Comment by hean01-cendio** [comment]
@Sturmungandir ah ok, that is a bug then. Let me see if i can reproduce with one of our Win10 that is joined a domain which i belive is your case ?

**Comment by hean01-cendio** [comment]
@Sturmungandir I could not reproduce your issue, got connected without prompt for password against a Window 10 joined a AD with a AD user.

The only way I could reproduce your case with login prompt was to provide invalid domain, username or password.

My only idea about this is that there is a bug regarding the above three strings sent to server. Is your username / password plain ASCII or does they container UTF-8 characters ?

**Comment by Sturmungandir** [comment]
It is plain ASCII. Could there be an AD policy that forces the user to actually type her password regardless?

**Comment by markd89** [comment]
With 1.82, I had a Gnome Quicklaunch which ran script which looked like this:

##! /bin/sh
rdesktop -u mark -g 1280x960 -x:m -z -a16 10.0.0.3

In 1.82, this would connect me to the server and I'd see the Windows login screen where I would type the password.

1.83 broke this and running the same Quicklaunch now  "nothing happens". I think that is because there is no terminal window visible to show me the Password prompt.

I worked around my problem using ssh-askpass as suggested above and I am fine with that workaround. 

I'm commenting to suggest that when an official release happens, this change of functionality should be documented. For people doing things like me or the OP, they cannot just upgrade rdesktop and have things work exactly the same as before.

I hope this helps. Thanks for the nice work!
Mark

**Comment by nospam3159** [comment]
We are in the year of 2018 and one could easily argue that passwords should have no place in this day and age of readily available public/private key authentication schemes. Along the same line one could argue that access control for RDP is best handled by other methods, or at least that is how my systems are setup. I do consider it a bug to mandate the use of passwords, and the existence of this bug report suggests I am not the only one who find this regression problematic.

Please consider merging my pull request, or be open for other suggestions on how to keep rdesktop an easy to use component for accessing hosts secured by other means than pure RDP.

**Comment by hean01-cendio** [comment]
> I do consider it a bug to mandate the use of passwords, and the existence of this bug report suggests
>I am not the only one who find this regression problematic.

The main reason for mandating the use of password before connection is that an RDS environment requires credentials to be provided upon a connection. This is new to RDS and does not apply to terminal service running on a windows workstation.

Yes it is a regression, but can also be handled with suggested solutions in this issue for those cases.

**Comment by nospam3159** [comment]
> This is new to RDS and does not apply to terminal service running on a windows workstation.

Neither does it apply to connecting to VirtualBox nor to xrdp, to restate the obvious.

> Yes it is a regression, but can also be handled with suggested solutions in this issue for those cases.

Introducing a password is a regression, indeed. A clean fix would be to revert that behaviour and encourage the use of "-p -" when needed. Or, if possible, detecting that the server is one of these RDS environments and only prompt for password when required. As far as I can see, no one has suggested any of those ways to resolve the regression, and I do agree they would not be reasonable.

However the only solution I see suggested is adding an option to not prompt for a password. Supplying a fake password is a work around, not a solution. It is bad practise and somewhat confusing to request something other than what is desired. A user fronting interface should be user friendly, and as obvious as possible.

What problems do you see in merging my pull request? I know there are documentation issues, which I could fix if seeing an opening for it to become accepted.

**Comment by trentasis** [comment]
I'm agree with, @Sturmungandir this is a problem and with environments where cmd is not visible, like thinclients.... Will be great to allow no ask this pwd from cmd
Thanks

**Comment by Rakasa** [comment]
I find it very illogical to add an additional option to allow not providing the password when omitting the '-p' option already logically implies this (and worked fine for most use cases).  Rather than add an additional, logically redundant option, I recommend reverting the 'password always required' aspect, and if the remote server does require the password to be provided for the initial connection, either prompt for it then (if feasible) or a clean exit with a message stating that the remote host is requiring the password to be provided for the initial connection.

One of the environments I work in has Windows 2016 servers using a two factor authentication that starts with providing a challenge PIN on the usual login screen after connecting, and I have to enter that challenge PIN into my f2a device and provide the server with the response PIN the 2fa device spits out.  On any wrong PIN, the connection is immediately terminated.  When forced to enter _something_ on the cli for rdesktop to even connect, it is guaranteed to be the wrong PIN, as I don't even have the challenge PIN yet, and the connection is immediately terminated, making every build containing this change completely impossible to use in those environments.

-- Rakasa

**Comment by hean01-cendio** [comment]
> I recommend reverting the 'password always required' aspect, and if the remote server does require the password to be provided for the initial connection, either prompt for it then (if feasible) or a clean exit with a message stating that the remote host is requiring the password to be provided for the initial connection.

NLA requires password to be provided before connection, however the change I made does require this password prompt regardless of NLA is in use or not. The proper change to this problem should be to only ask for password if NLA is in use.

@Rakasa can you confirm that you can not use 2FA in combination with NLA enabled ?

**Comment by uglym8** [comment]
Just to make sure that we're all on the same page here (i.e. all use cases are acknowledged) I'd like to remind about another case when @hean01-cendio's changes are very convenient i.e. redirection (check #262 for use case's description).

So to sum it up it seems that there are two cases (at least, for now) when to have a password is beneficial:

1.  NLA case
2. Redirection case

**Comment by Rakasa** [comment]
I fear I do not know enough to know what NLA is, and therefore can't definitively confirm it is not in use.  However, I can say using the default stock binary that comes with Fedora, I do not have to enter a password multiple times, and I get the login screen that prompts me with my challenge PIN to input into the 2fa device and get the response PIN.  Based on that coupled with the descriptions here, I would logically deduce neither NLA nor redirection is in use in these environments, and would be incompatible with the 2fa system in use, so installing the 2fa package must disable/remove them or handle them itself.  (I do not know what the 2fa system is; I'm "just a user" in these customers' environments).


All binaries using this change get the connection immediately terminated with a 'failed login' logged on the server side and never drawing the initial login window as it would be impossible to enter a correct response PIN without getting the challenge PIN first.  (A little more detailed description in #262)

-- Rakasa

**Comment by hean01-cendio** [comment]
Commit bc727e7 adds the ability to provide an empty password that will disable the prompt for password and take you to the remote login screen.
