### ISSUE TITLE
slow rendering since el capitan

### ISSUE THREAD

**Issue by SpunkyIceke** [rdesktop/rdesktop#27]
Hello,

Apparently rdesktop is broken since el capitan. Rendering of rdesktop is very slow and on yosemite it works flawlessly.

Has anyone noticed this?

Thanks,
Bert
##

**Comment by britcan** [comment]
I encountered this problem approximately 10 months ago on two different Linux distributions. For many years now, I have used rdesktop running on a linux desktop, usually KDE, to log into my main production Windows laptop when working in my office. I started doing this in the Windows XP days and continued with Windows 7. Windows XP Pro and Windows 7 Pro allow remote login. Home (Premium) does not.

This approach worked very well until approximately 10 to 12 months ago (March - May 2015) when the X11-driver and X11-server files were updated. After the update, the rendering in rdesktop slowed down marketedly to the point where it is no longer practical to use it. The best way to demonstrate the problem is to remotely log into a Windows desktop using rdesktop and then open a very large text file in notepad and attempt to scroll. When rdesktop is working properly, it easly keeps up with the remote Windows 7 session. When it is not, you can no longer work with a simple large text file because the rendering is so slow. 

I have verified this on two Linux distributions: PCLinuxOS and KUbuntu. It is easy to reproduce using KUbuntu liveDVDs for versions 12.04 and 14.04. rdesktop works fine on version 12.04 but exhibits the problem in 14.04. In my main PCLinuxOS desktop system, I froze the X11-server and X11-driver files in the package manager in order to be able to continue to use rdesktop. I knew at the time that I would be living on borrowed time as, eventually, other applications and utilities would stop working with the old X11- drivers and software. This has indeed happened now with the update of Google-Chrome from version 49.x to 50.x. Version 50.x will not play video with the old X11 drivers and server software. Keeping Google-Chrome at version 49.x obviously leaves open security vulnerabilities. 

I will do some trial and error work to try to isolate which specific X11-driver and/or X11-server update files are causing the problem and report back on this forum.

**Comment by britcan** [comment]
I attempted to isolate a subset of X11 updates causing the rdesktop slowdown but was unable to due to too many dependencies. So, hopefully, the developer or developers can update rdesktop to work efficiently with the most up-to-date X11 drivers and all other dependent libraries. I really don't think it will be usable until this happens.

**Comment by hean01-cendio** [comment]
What version of X11 is known to produce the issues with slow rendering ?

**Comment by britcan** [comment]
Will get back to you over the weekend. Will have to start with X11 on PCLinuxOS which I know is not exactly mainstream but what I use on a regular basis. Will try to get the same info for Ubuntu after that.

**Comment by britcan** [comment]
Sorry for the late reply. I used the following command to get what I hope is the X11 version on which rdesktop works properly: 
xdpyinfo | grep version
Result:
version number: 11.0
X.Org version: 1.14.6

I also took two screenshots of Synaptic which I attach below. I don't know if they are any use to you or not. As mentioned previously, I am using Texstar's PCLinuxOS which I realize is not exactly mainstream. If I get time, I will run run the live DVDs for Ubuntu 12.04 and 14.04 to contrast the difference. redesktop works flawlessly in 12.04 but exhibits the same slow rendering in 14.04.

![synaptic_showing_x11-1](https://cloud.githubusercontent.com/assets/15957923/16422461/73b1b020-3d26-11e6-8a35-72eda32e4831.jpg)

![synaptic_showing_x11-2](https://cloud.githubusercontent.com/assets/15957923/16422471/7aeba260-3d26-11e6-8986-655b6964f4aa.jpg)

**Comment by britcan** [comment]
Today I ran some experiments using live DVD sessions to try to home in on which version change of X11 caused the rdesktop slow down. As mentioned previously, I use KDE as my main Linux desktop. Unfortunately, I was unable to get the live DVDs for KUbuntu versions 14.04.1, 14.04.2 and 14.04.3 to boot on my test computer which is a dated HP Compaq nx7400 laptop. I was able to run tests using live DVDs for Ubuntu (Unity desktop) 14.04.2, 14.04.3 and 14.04.4. I ran the terminal command "xdpyinfo | grep version" to determine which version of X11 are installed. Here are the results:

Ubuntu 14.04.2     Release date: 2015-Feb     X.org version: 1.16.0
Ubuntu 14.04.3     Release date: 2015-Aug     X.org version: 1.17.1
Ubuntu 14.04.4     Release date: 2016-Aug     X.org version: 1.17.2

Much to my surprise, I was NOT able to reproduce the rdesktop slowdown. It worked fine on all three live DVDs.
 
I further tested rdeskop on a fully updated KUbuntu 14.04.x laptop rdesktop logging into a fully updated Windows 7 Pro laptop again with no problems. The X.org version on KUbuntu is 1.15.1.

The results are therefore inconclusive. I am now suspicious that the original Windows 7 Professional system into which I normally log using rdesktop might be corrupted somehow and am also suspicious that the problem might be KDE affecting rdesktop. I will investigate these suspicions over the next several weeks. Until then, I think it is too early to conclude that there actually is a problem with rdesktop.

**Comment by britcan** [comment]
One last comment. It is not the Windows 7 Pro systems. I retested my original PC Linux system using both the KDE and XFCE4 desktops and confirmed that rdesktop slows down dramatically to the point where it is unusable. I tested this on logging into two completely different Windows 7 Pro systems and got the same result. The version of X.org that works on PCLinuxOS is 1.14.6. So the problem seems to be related to the distribution and perhaps the desktop environment.  Based on 0bs3v3r's input, it appears it is not limited to just PCLinuxOS and Linux. If I build a non-PCLinuxOS full system, I will test this as the first order of business and report back (perhaps a post summer project). Live DVDs are great but they sometimes mask things. I know of examples where things worked fine on the live DVD but failed on a proper install.

**Comment by britcan** [comment]
I have one amendment and possible correction to my June 28th post. I reported that I was not able to reproduce the rdesktop slowdown when testing from live DVDs. There may have been a flaw in my approach as I did these tests from a dual core i5 laptop but all other of my rdesktop uses are on drastically less powerful machines which is why the problem was so obvious in the first place. I normally log in remotely from a Zotac mini box with an AMD quad core A4-5000 CPU and used to use an even older Core 2 Duo business laptop. Both are fine when using the old version of X11 but are unusable with the newer and up-to-date versions. I get the feeling that the i5 laptop compensated for the X11 related slowdown with its inherent processing power.  

0bs3v3r, perhaps you can comment on the age / type of CPU of the Mac computer on which you experienced the rdesktop slowdown.

**Comment by britcan** [comment]
I have a positive update to report. The reported rdesktop performance issue appears to no longer be a problem on PC Linux OS. I ran a full update today on the system I was using as the reference for this problem and everything is working fine. You may recall from earlier posts that I had held back updating this system in order to keep rdesktop usable (i.e. keep the older X11 files in place). It appears that whatever was causing the slowdown has been optimized or fixed. I have not verified this on any other (more mainstream) distributions such as (k)Ubuntu.

**Comment by gohrner** [comment]
(Linux, KDE Neon based on Ubuntu 16.04, Intel graphics, Modesetting driver)

I also experience this slowdown in specific circumstances - normal graphics performance is ok, but rendering of specific text widgets in specific applications is incredibly slow. One example is the query execution log from IBM Data Studio. X will busy out one CPU core and, as rdesktop grabs the keyboard, make the whole system unusable until output finally finishes... (While it's running, mouse works just fine and I can also switch windows, but I have no keyboard as it's redirected to rdesktop... Pretty annoying, as this means I even cannot kill rdesktop - which, being busy as it is, will also not react to window close requests using the mouse...

Maybe that's not really related to the X version, but to the video driver? I'm also using an Intel based card, and the Intel Linux drivers appear to be pure crap somehow...

**Comment by bulibuta** [comment]
I am having the same problem on OpenBSD for the last months. The intel drm driver here is the same as on Linux so I am pretty sure this is related to the kernel not the actual application. Unfortunately I can not think of a way to fix it without reverting.

**Comment by markmr** [comment]
For AMD Radeon this issue seems to be solved, on Debian at least. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=762081
