### ISSUE TITLE
1.8.4 still gets RSA_get0_key invocation in ssl.c:rdssl_rkey_get_exp_mod() backwards

### ISSUE THREAD

**Issue by cemeyer** [rdesktop/rdesktop#296]
https://github.com/rdesktop/rdesktop/compare/v1.8.3..v1.8.4#diff-5931449ee480a798cabbfe5a0df96da8R232

https://github.com/rdesktop/rdesktop/blob/v1.8.4/ssl.c#L232

```
rdssl_rkey_get_exp_mod(RDSSL_RKEY * rkey, uint8 * exponent, uint32 max_exp_len, uint8 * modulus,
		       uint32 max_mod_len)
{
	int len;

	BIGNUM *e = NULL;
	BIGNUM *n = NULL;

#if OPENSSL_VERSION_NUMBER < 0x10100000L
	e = rkey->e;
	n = rkey->n;
#else
	RSA_get0_key(rkey, &e, &n, NULL);
#endif
```

Contrast with:

```
        void RSA_get0_key(const RSA *r,
                          const BIGNUM **n, const BIGNUM **e, const BIGNUM **d);
```

This was fixed silently in master with the unrelated change https://github.com/rdesktop/rdesktop/commit/a3dfceefc2c729243b71270e3f503fa2dd57ec8d 18 months ago.

**Comment by hean01-cendio** [comment]
Thank you for spotting this, i will do an 1.8.4.1 release with this fix.

**Comment by hean01-cendio** [comment]
What I understand this code affects the internal RDP encryption which is only used when TLS is not used. I have tried to find a test case (earliest RDP service I have is from Windows 7) but failed. I had to modify rdesktop code to be able to hit the code path were that code is used. However it is broken in an earlier stage the patch for 1.1 compability is not usable at all as it seems.

The follow up question is, how big is the impact of this beeing broken, what is your use case ?

**Comment by cemeyer** [comment]
I don't use `rdesktop` at all.

**Comment by hean01-cendio** [comment]
@cemeyer I see.

Here is my conclusion; The issue is related to using plain RDP connection, eg. not using TLS transport and when fixing the that issue it later fails by the OpenSSL 1.1 compability patch. This affects connections to very old RDP servers and I will not d a 1.8.4.1 release.

HEAD suffers from the same problem and with the move to GnuTLS this issue is solved. So I will focus to get rdesktop 1.9.0 out which will include the GnuTLS migration.
