### ISSUE TITLE
"next order pointer would overrun stream" error connecting to Windows Server 2003 R2

### ISSUE THREAD

**Issue by opoplawski** [rdesktop/rdesktop#320]
One of our users is reporting the following crash:

```
Connection established using SSL.
Protocol(error): rdp_protocol_error(), process_secondary_order(), next order pointer would overrun stream
0000 ff ff 18 04 05 10 01 40 01 00 10 59 0d 38 10 01 .......@...Y.8..
0010 cc 06 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
```
[on for pages....]

This message seems to have come in with the recent security fixes: https://github.com/rdesktop/rdesktop/commit/4dca546d04321a610c1835010b5dad85163b65e1

**Comment by opoplawski** [comment]
This does not appear to always happen - I can connect fine.

**Comment by CendioOssman** [comment]
Do you think you could work with the user to figure out when this happens? It will be difficult to fix without being able to reproduce it.

**Comment by sircrimer** [comment]
I get the following error 100% of the time after trying to establish a connection to a Windows 2000 Server. It works fine with a Windows 2003 Server.

`WARNING: Remote desktop does not support colour depth 24; falling back to 8
ERROR: rdp_protocol_error(), process_secondary_order(), next order pointer would overrun stream0000 ff ff 18 04 05 10 01 40 01 00 10 59 0d 38 10 01 .......@...Y.8..
0010 cc 04 28 00 40 04 28 00 40 04 28 00 40 04 28 00 ..(.@.(.@.(.@.(.
0020 80 04 28 00 00 04 28 00 00 04 28 00 00 04 28 00 ..(...(...(...(.
0030 80 04 28 00 80 04 28 00 80 04 28 00 40 04 28 00 ..(...(...(.@.(.
0040 40 04 28 00 40 04 28 00 40 04 28 00 40 04 28 00 @.(.@.(.@.(.@.(.`

**Comment by CendioOssman** [comment]
Not sure, I'll have to inspect things closer.

Unfortunately I have to say that this will not be prioritized very highly. Windows 2000 is extremely ancient and our focus is on current versions of Windows.

**Comment by grubba** [comment]
I seem to have this same issue with connecting to a Windows 2003 server.
It appears that the display window size affects whether it crashes or not.
My display is 3840x2160 pixels.
`rdesktop -g 90% host` crashes with
```
Failed to negotiate protocol, retrying with plain RDP.
WARNING: Remote desktop does not support colour depth 24; falling back to 8
ERROR: rdp_protocol_error(), process_secondary_order(), next order pointer would overrun stream0000 ff ff 18 04 05 10 01 40 01 00 10 59 0d 38 10 01 .......@...Y.8..
0010 cc 06 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
...
```
While `rdesktop -g25% host` seems to work.
```
```
$ rdesktop --version
rdesktop: invalid option -- '-'
rdesktop: A Remote Desktop Protocol client.
Version 1.8.4. Copyright (C) 1999-2011 Matthew Chapman et al.
See http://www.rdesktop.org/ for more information.
```

**Comment by vincentcox** [comment]
For those doing OSCP or infra penetration testing in really, really old environments:
`sudo apt install remmina`

![image](https://user-images.githubusercontent.com/9286611/58039272-8e731a00-7b32-11e9-8615-6836641c73a3.png)

I can understand the author's decision to keep the focus on new Windows systems. But I wanted to share my alternative for the ones ending up here.

**Comment by CendioOssman** [comment]
I'm seeing several reports here and the main thing they have in common is using the old plain RDP protocol. Most servers should be using TLS these, so that's probably why only some are affected.

**Comment by sircrimer** [comment]
On Arch linux with rdesktop Version 1.8.6, I get the following error when connecting to the same Windows 2000 server.

Autoselected keyboard map en-us                                                                                                                                                               
ERROR: Failed to extract public key from certificate
ERROR: recv: Connection reset by peer

**Comment by malxau** [comment]
For what it's worth, I also hit this, spent a bit of time digging into it, and the fix is commit 5c900521f315a433735f34815289d0d30fc5b464 .  For some other reason master still isn't working for me, but for anyone hitting this, the 1.8.6 code is trying to decrypt zero bytes of data and is then left trying to validate cyphertext, and failing.

**Comment by CendioOssman** [comment]
@malxau, are you testing with 2003 or something newer? I'm afraid I don't have any such old servers here and I'm not getting any errors with a 2008 R2 using plain RDP.

**Comment by malxau** [comment]
Yes, this is on 2003.  Note the fix is in the 1.8.x branch, so builds from there work with 2003 correctly.

2000 still does not work correctly.  I've tried digging into this but haven't been able to figure it out just yet.  The last version that works against 2000 correctly is 1.8.2.

NT4 works like a charm (and always did.)

**Comment by CendioOssman** [comment]
That's odd. Are you getting the exact same error output with `master`? Or are there some differences?

**Comment by malxau** [comment]
`master` is completely dfferent and seems to introduce quite a number of issues.  Firstly and most obviously, it always prompts for a password which on these systems makes no sense because they do not support NLA.  I believe that an empty string is effectively the same as previous behavior, so that's what the rest of this post is doing.

For 2003, `1.8.x` works and `master` fails.  I tried to investigate this by outputting the contents of buffers both for send and recv between the two branches to "spot the difference" but there are many differences due to protocol support which made this approach not fruitful, and I ended up reverting those changes.  `master` connecting to 2003 gives something like:
```
Password: 
Protocol(warning): Protocol negotiation failed with reason: SSL not allowed by server
Retrying with plain RDP.
Protocol(error): rdp.c:184: rdp_recv(), not enough data for PDU
0000 03 00 00 30 02 f0 80 68 00 01 03 eb 30 22 08 00 ...0...h....0"..
0010 14 76 33 3a 92 7a 1b 25 8e 4c dd 31 92 76 1c 51 .v3:.z.%.L.1.v.Q
0020 46 bf fb ee 5e cf c9 b8 65 a4 e7 11 03 d1 33 eb F...^...e.....3.
```

On 2000 the output is different between `master` and `1.8.x` but I suspect the cause is the same.  Although 1.8.2 can connect to the 2000 machine correctly, even the Microsoft client cannot connect to it claiming a licensing problem (which is bogus since it's running in remote administration mode.)  I suspect there's an expired cert somewhere here.  Note specifically that neither displays the "SSL not allowed by server" message which they really should, implying that this failed in the SSL negotiation somehow.   `master` ends up getting a server side disconnect, whereas `1.8.x` dumps out a fairly large stream overrun message.

`master`:
```
Password: 
Core(error): tcp_recv(), recv() failed: Connection reset by peer
```

`1.8.x`
```
WARNING: Remote desktop does not support colour depth 24; falling back to 8
ERROR: orders.c:1265: process_secondary_order(), next order pointer would overrun stream0000 80 87 39 5a 12 6b 7d 37 4f c3 b2 03 00 00 02 08 ..9Z.k}7O.......
0010 03 02 00 43 00 00 01 00 00 00 00 00 80 00 00 00 ...C............
0020 80 00 80 80 00 00 00 80 80 00 80 00 80 80 80 80 ................
0030 80 c0 c0 c0 ff 00 00 00 ff 00 ff ff 00 00 00 ff ................
0040 ff 00 ff 00 ff ff ff ff ff ff 80 80 ff 80 80 ff ................
0050 80 80 ff 80 80 ff 80 80 ff 80 80 ff 80 80 ff 80 ................
0060 80 ff 80 80 ff 80 80 ff 80 80 ff 80 80 ff 80 80 ................
0070 ff 80 80 ff 80 80 ff 80 80 ff 80 80 ff 80 80 ff ................
0080 80 80 ff 80 80 ff 80 80 ff 80 80 ff 80 80 ff 80 ................
```
(more packet contents available on request)

With NT4, `1.8.x` works correctly whereas `master` appears to connect but display no UI.  `xlsclients` does not list rdesktop as communicating with X at all.  The output (which I think is misleading) is below, but note that the disconnect happens after a minute presumably because the server gets no logon input and kills the session.  For completeness, I can connect to an 8.1 machine and get UI, so my `master` build isn't always broken.
```
Password: 
Sound(error): rdpsnd_init(), failed to register rdpsnd / snddbg virtual channels
Core(warning): Initializing sound-support failed
Core(error): rcp_recv(), connection closed by peer
```

My own 2c though is these seem like four different issues to the one this issue is about, which has been fixed.

**Comment by CendioOssman** [comment]
Thanks for the extra details. That should hopefully make it somewhat easier to debug this.

Unfortunately it won't see much attention from me. We don't have any such old machines, and we can't really prioritise fixes for such old software.

If someone else figures out the issue and does a PR then we can have a look at that though.

**Comment by malxau** [comment]
I'd love to help, but unfortunately I know basically nothing about the protocol which is really at issue here.  I tried looking into the NT4 case expecting it to be the simplest, but the hang occurs because one side or the other is just waiting for more data from its peer until the server eventually times out and kills the connection.  I can collect packet traces and share them with somebody who knows what they're looking it if it's helpful.

So as of now, the 2000 one is the only one I haven't looked into, and I'm one for three...

**Comment by CendioOssman** [comment]
`master` has gotten a fix for XP now, and #348 has one more that makes XP work for me. Could you guys here test that patch with `master` and see if it solves the issues you've been seeing or if there are more problems?

**Comment by haggl** [comment]
Connections to xrdp (0.9.9-1 on Debian GNU/Linux) are working again with 1.9.0-beta.
\o/

**Comment by CendioOssman** [comment]
Fantastic. I'll consider this resolved then.
