### ISSUE TITLE
which version starts to support windows10

### ISSUE THREAD

**Issue by zhangtao4096** [rdesktop/rdesktop#384]
hi
I want to ask which version starts to support windows10?
Thanks!

**Comment by brunodOut** [comment]
Hello @zhangtao4096,

I'm sorry you had to wait this whole time for a reply.

By supporting windows 10 you mean compiling and running rdesktop on W10 or connecting to a W10 server?

In the second case, it should work fine in most of the recent versions since 1.8.6, and lacking some features but working since W10 was born, although I only connected to W10 machines on 1.9.0. If you are (or were) having some difficult with running it on W10, it would be great if you could report it into a new issue (where the specific difficulties would be the main topic).

About running on W10, there's a comment on [this issue](https://github.com/rdesktop/rdesktop/issues/260) suggesting it might be possible, but I cannot confirm whether it will work or how hard it would be to achieve that.
