### ISSUE TITLE
Automatic Timeout: "Thin Client" Using rdesktop

### ISSUE THREAD

**Issue by tkbton** [rdesktop/rdesktop#46]
Is there an automatic timeout built into rdesktop? I'm trying to use rdesktop on a Raspberry Pi to create a thin client that logs into Windows Server 2012. I've checked the Windows server and no apparent issues there. I've set everything up so rdesktop automatically connects to the server at login but does not actually log into the server (allowing whichever user who is sitting at the terminal to log in directly on the server). rdesktop will stay connected to the server for a short period of time then shut off and start up (connect to server) again. It does this 6 times and then stops connecting.

Another minor issue I'm having is that rdesktop won't let me omit a username. I've tried quotation marks, etc.

Any help is appreciated!

**Comment by hean01-cendio** [comment]
The actual timeout is configured at the RDP server, nothing to do with rdesktop client. I think you can change this timeout with a registry setting named LoginTime, you will find your answer if you google for it.

For the second issue, running `rdesktop -u ''` works as expected. Username is omitted and I get user/password fields to enter my credentials into, instead of the normal password field only.
