### ISSUE TITLE
No sound on my local system

### ISSUE THREAD

**Issue by blimjoe** [rdesktop/rdesktop#49]
Hi,

I'm trying to run rdesktop on a 96board which is Debian OS to connect it with an Windows 7 computer. But there's no sound on my board after the following command `rdesktop -a 16 -g 1280x1080 -r sound:local xxx.xx.xx.xxx:3389` xxx.xx.xx.xxx is my ip address. 
I've also tried `-r sound:local:alsa` and `-r sound:local:oss` as I've seen somewhere I googeled. But it still not works. 
In terminal, the log was 

> /dev/dsp: No such file or directiory

> WARNING: no working audio-driver found.

But actually, my audio driver on board is working.

**Comment by cferry322** [comment]
I have experienced the same issue.  I have successfully run RDP on my Raspberry Pi running Raspbian, which I then use to connect to my work terminal (Windows 7 Machine).

Anyway, sound works when I am at work, and sound works on Raspbian, but when I RDP into my Win7 machine, same issue.  Sorry this is little help, just wanted to report that you are not alone.  I will try looking around its been bugging me for a while, but great Remote environment otherwise.

**Comment by hean01-cendio** [comment]
Which audio libs are used on your linux disrtibution pulseaudio/alsa/other or oss ?

**Comment by blimjoe** [comment]
It's alsa.

**Comment by hean01-cendio** [comment]
I just verified that alsa audio driver works as expected. It could be that your alsa configuration has problems and 'default' device is something you dont expect it to be eg phones out instead of line or even another audio card eg HDMI etc.

Check `aplay -L` command output for available output devices.
