### ISSUE TITLE
Smartcard logon with PIN PAD readers

### ISSUE THREAD

**Issue by HenryJacques** [rdesktop/rdesktop#57]
The current rdesktop design doesn't allow PIN PAD readers (secure PIN reader which only allow the PIN code to be entered into the integrated keyboard).
Indeed the "-p" argument should take the PIN code but such readers sometimes integrate the secure PIN entry feature (e.g. http://www.trueb.ee/services-and-products/card-readers)

Regards
##

**Comment by derfian** [comment]
@uglym8, how much of this would be solved by #238?

**Comment by uglym8** [comment]
@derfian, I'd say that it should work. 
But to be on the safe side I'll verify myself that PIN verification works in general.
After that I might try to verify that smartcard login works  in Windows. 
Never tried it before though.
So it seems that I finally will get a chance to try it:)

**Comment by uglym8** [comment]
@derfian when I said it should work I only meant that PIN verification should work in general.
Regarding smart card authentiocation with "-p":  I'll have to investigate this matter a little bit.

**Comment by uglym8** [comment]
@derfian when I said it should work I only meant that PIN verification should work in general.
Regarding smart card authentiocation with "-p":  I'll have to investigate this matter a little bit.

**Comment by uglym8** [comment]
Yes, it must work.

Basically you either enter pin using keyboard and Class 1 reader (simple) in which case PIN is sent to the TS and from there back to smartcard.
Or you can use Class 2/3 reader and enter PIN on pinpad without sending it to the TS and back.

I'm closing this now as fixed by #238
Reopen it please if I've missed something.
